//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AK_HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_logins
    {
        public int Id { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> login_at { get; set; }
        public string login_from { get; set; }
    
        public virtual Ak_Users Ak_Users { get; set; }
    }
}
