//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AK_ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AK_Modules()
        {
            this.AK_Roles_lines = new HashSet<AK_Roles_lines>();
        }
    
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public string Title { get; set; }
        public string url { get; set; }
        public string Header { get; set; }
        public string SQLSelect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AK_Roles_lines> AK_Roles_lines { get; set; }
    }
}
