//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AK_HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Roles_lines
    {
        public int Id { get; set; }
        public Nullable<int> role_id { get; set; }
        public int module_id { get; set; }
        public Nullable<int> module_name { get; set; }
        public Nullable<bool> acesss { get; set; }
        public Nullable<bool> read { get; set; }
        public Nullable<bool> create { get; set; }
        public Nullable<bool> update { get; set; }
        public Nullable<bool> delete { get; set; }
    
        public virtual AK_Modules AK_Modules { get; set; }
        public virtual AK_Roles AK_Roles { get; set; }
    }
}
